### ISSUE TITLE
Setting up Visual Studio for debugging extensions. This one-time operation may take a minute or more.

### ISSUE THREAD

**Issue by niemyjski** [appveyor/ci#1608] opened 2017-06-13 23:12 UTC
Setup build image with vs debugging extensions...

I'm not sure how to go about doing this, but every build is 2 minutes longer as it's waiting for `Setting up Visual Studio for debugging extensions. This one-time operation may take a minute or more.`

**Comment by FeodorFitsner** [comment] 2017-06-14 05:01
Could you please do "Hello, world" project in a public repo setting up extensions during the build, so we can use it for build worker image "warm up"?

**Comment by roji** [comment] 2017-06-22 09:54
Duplicate of #1391 ("hello world" project still not submitted...)

**Comment by roji** [comment] 2017-06-22 10:27
[See this](http://comealive.io/AppVeyor-Times-Out-VSIX/) for a workaround.

**Comment by IlyaFinkelshteyn** [comment] 2017-06-22 19:31
@roji Thanks a lot!

**Comment by igitur** [comment] 2019-12-12 10:40
> [See this](http://comealive.io/AppVeyor-Times-Out-VSIX/) for a workaround.

@roji The link is dead. Can you please provide the work-around here on the issue page?

**Comment by FeodorFitsner** [comment] 2019-12-12 18:38
You can initialize Visual Studio Experimental Instance with the following script"

```posh
& "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe" /RootSuffix Exp /ResetSettings General.vssettings /Command File.Exit
```

We'll add that into build image during the next update.

**Closed** 2020-01-10 18:20 UTC
Labels: in progress
