### ISSUE TITLE
Enable URL for HipChat server to be specified for notifications

### ISSUE THREAD

**Issue by tvanfosson** [appveyor/ci#804] opened 2016-05-13 00:13 UTC
I would like to be able to send notifications to a HipChat room on our private HipChat server but there does not seem to be a way to specify the server URL in the notifications interface.

**Comment by FeodorFitsner** [comment] 2016-05-13 02:59
It's duplicate of https://github.com/appveyor/ci/issues/65

**Comment by FeodorFitsner** [comment] 2016-05-17 04:06
It's been deployed. There is a new "HipChat Server URL" setting on UI and `server_url` in appveyor.yml.

**Closed by FeodorFitsner** 2016-05-17 04:06 UTC
Labels: in progress

**Comment by tvanfosson** [comment] 2016-05-17 04:52
Awesome. Thanks for the quick turn around.  I've got it set up and running.
