### ISSUE TITLE
Python 3.12

### ISSUE THREAD

**Issue by EwoutH** [appveyor/ci#3879] opened 2023-06-14 11:43 UTC
Python 3.12 is now in the [Beta phase](https://peps.python.org/pep-0693/) and will be released in a few months. This means it's going to be heavily tested the next few months. It would be great if AppVeyor could add Python 3.12 to it's images.

- [x] Ubuntu images
- [x] Windows images
  - [x] `Visual Studio 2019` image
  - [x] `Visual Studio 2022` image
- [x] macOS

**Comment by OwenMcDonnell** [comment] 2023-06-15 21:52
We wouldn't want to risk breaking any other users builds by installing a beta. But you could always add something like this to your `appveyor.yml` config file for your own testing. 

```
install:
  - ps: |
      $version = "3.12.0"
      $beta = "b2"
      Write-Host "Installing Python $version" -ForegroundColor Cyan

      $downloadUrl = "https://www.python.org/ftp/python/$version/python-$version$beta-amd64.exe"
      Write-Host "Downloading $($downloadUrl)..."
      $exePath = "$env:TEMP\python-$version$beta.exe"
      (New-Object Net.WebClient).DownloadFile($downloadUrl, $exePath)
      
      Write-Host "Installing..."
      cmd /c start /wait $exePath /quiet TargetDir="$targetPath" Shortcuts=0 Include_launcher=1 InstallLauncherAllUsers=1 Include_debug=1
      Remove-Item $exePath
      
      Start-ProcessWithOutput "$targetPath\python.exe --version"
      
      Write-Host "Installed Python $version" -ForegroundColor Green
```

**Comment by EwoutH** [comment] 2023-06-19 15:18
Users will only install 3.12 if they specifically select it right? I'm not talking about changing the default Python version, just adding another version.

**Comment by hugovk** [comment] 2023-09-03 19:58
The [3.12 release candidate 1](https://discuss.python.org/t/python-3-12-0-release-candidate-1-released/31137?u=hugovk) is now out (with RC2 due next week), and the release manager is asking maintainers to test:

> There will be **no ABI changes** from this point forward in the 3.12 series, and the goal is that there will be as few code changes as possible.
> 
> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.

**Comment by hugovk** [comment] 2023-10-02 19:56
Python 3.12.0 final is now out! 🚀 

https://discuss.python.org/t/python-3-12-0-final-is-here/35186?u=hugovk

**Comment by mkleehammer** [comment] 2023-10-10 14:57
Is there an ETA for Python 3.12 support to be released?  Thanks.

**Comment by jfabiani** [comment] 2023-10-13 03:52
I know that people are saying to move to psycopg3 but I have a lot invested in psycopg2.  So please release a version for python 3.12

**Comment by EwoutH** [comment] 2023-10-13 18:07
Sadly it's hard to take Appveyor serious as a CI vendor anymore, especially with such a heads-up.

On GitHub Actions, Python 3.12 was natively [available](https://github.com/actions/runner-images/issues/6473) from the alpha phase, almost a year ago.

**Comment by CRD716** [comment] 2023-10-15 00:50
@OwenMcDonnell Any progress updates?

**Comment by knightofcookies** [comment] 2023-10-17 05:45
SQLAlchemy requires psycopg2 to work with PostgreSQL and psycopg2 cannot be installed for Python 3.12 on Windows. This issue was [referenced](https://github.com/psycopg/psycopg2/issues/1628#issue-1923756958) as the cause.
I'm flabbergasted to see that something so important isn't working with the latest version of Python. It's unbelievable.

**Comment by OwenMcDonnell** [comment] 2023-10-17 17:22
Apologies for the delay. Python 3.12 will be part of the next image update, which is being worked on now. Should be within a week.

**Comment by OwenMcDonnell** [comment] 2023-10-21 03:21
Ubuntu 22.04 image has been [released](https://www.appveyor.com/updates/2023/10/17/) with support for Python 3.12.
Visual studio images are up next.

**Comment by treyhunner** [comment] 2023-10-22 04:10
Specifying `stack: python 3.12` with image `Ubuntu2024` doesn't seem to work. Using `tox` shows an `InterpreterNotFound` error.

**Comment by OwenMcDonnell** [comment] 2023-10-25 03:36
> Specifying `stack: python 3.12` with image `Ubuntu2024` doesn't seem to work. Using `tox` shows an `InterpreterNotFound` error.

What are you actually using as an image name. `ubuntu2004` or `ubuntu2204`?

**Comment by OwenMcDonnell** [comment] 2023-10-27 21:36
A new VS2019 image has been deployed including python 3.12.0, documentation for which is awaiting a new VS2022 image which is currently being created. 
Feel free to try out the new `Visual Studio 2019` image and share any feedback.

**Comment by sbraz** [comment] 2023-10-29 13:12
Hi, would it be possible to add it to macOS images too please?

**Comment by OwenMcDonnell** [comment] 2023-10-31 00:29
> Hi, would it be possible to add it to macOS images too please?

Yes, that is planned. Can't give a definite date yet, but in the near future.

**Comment by OwenMcDonnell** [comment] 2023-10-31 00:30
Both `Visual Studio 2022` and `Visual Studio 2019` images have both been updated to include Python 3.12.0.

**Comment by EwoutH** [comment] 2023-10-31 06:00
Seeing multiple projects having successfully used Python 3.12 in CI, I will mark this issue as resolved! @OwenMcDonnell, thank you for your effort!

Python 3.13 beta will start in June 2024. That’s the point many maintainers will want to start testing Python 3.13. It will be great if AppVeyor could add Python 3.13 directly when the first beta is released. Note that GitHub Actions already has Python 3.13 support (https://github.com/actions/python-versions/commit/e642abaef814f4d4a6bfe1741f814e08dbbc2484).

**Comment by hugovk** [comment] 2023-10-31 06:51
For comparison, here's how long it took for other releases:

* 2019: Python 3.8: 25 days
* 2020: Python 3.9: 21 days
* 2021: Python 3.10: 28 days
* 2022: Python 3.11: 14 days
* 2023: Python 3.12: 28 days

And this year compared to other CIs:

🥇   13 hours: GitHub Actions ↔️
🥇   13 hours: Azure Pipelines ↔️
🥉   20 days: Travis CI ⬆️
4️⃣    28 days: AppVeyor ⬇️

**Comment by sbraz** [comment] 2023-11-01 00:34
@OwenMcDonnell should I open a separate issue for Python 3.12 on macOS images?

**Comment by OwenMcDonnell** [comment] 2023-11-02 04:04
> @OwenMcDonnell should I open a separate issue for Python 3.12 on macOS images?

I'll just re-open this issue and close once macOS images are updated. I can't promise anything sooner than a week, but likely sooner than 2 weeks.

**Comment by xqt** [comment] 2023-11-06 09:40
What about Python 3.12 on Windows images?

**Comment by hugovk** [comment] 2023-11-06 11:17
@xqt Available since last week: https://github.com/appveyor/ci/issues/3879#issuecomment-1786252102

**Comment by xqt** [comment] 2023-11-06 16:16
> @xqt Available since last week: [#3879 (comment)](https://github.com/appveyor/ci/issues/3879#issuecomment-1786252102)

It is not documented then:
https://www.appveyor.com/docs/windows-images-software/#python

**Closed as completed** 2024-05-22 05:18 UTC

**Comment by hugovk** [comment] 2024-05-22 18:47
> Python 3.13 beta will start in June 2024. That’s the point many maintainers will want to start testing Python 3.13. It will be great if AppVeyor could add Python 3.13 directly when the first beta is released. Note that GitHub Actions already has Python 3.13 support ([actions/python-versions@e642aba](https://github.com/actions/python-versions/commit/e642abaef814f4d4a6bfe1741f814e08dbbc2484)).

Python 3.13 is now in beta and it's time for maintainers to start testing:

* https://discuss.python.org/t/python-3-13-0b1-now-available/52891

**Comment by dakotath** [comment] 2024-07-24 03:18
lol me and some friends got Python3.12.4 on Wii Linux with working pip. Slow asf but funny as heck.
