### ISSUE TITLE
Feature request: Permalinks for "latest result" artifacts

### ISSUE THREAD

**Issue by ulrichb** [appveyor/ci#403] opened 2015-09-09 11:04 UTC
At the moment the "latest" artifacts cannot be downloaded over a stable URL.

E.g. for the "latest" successful build:
`https://ci.appveyor.com/project/<user>/<project>/artifacts/latest_successful/<artifact_file_path>`

E.g. for the "latest" successful build per branch:
`https://ci.appveyor.com/project/<user>/<project>/artifacts/<branch_name>/latest_successful/<artifact_file_path>`

**Comment by frankmorgner** [comment] 2015-09-14 08:28
Artifacts should also be accessible by specifying the build configuration. See also this request from 2014 http://help.appveyor.com/discussions/questions/516-url-for-latest-build-artifact is related

**Comment by kzu** [comment] 2016-01-16 20:17
:+1:

**Comment by sschuberth** [comment] 2016-02-04 09:17
For reference, the discussion was started by the OP at http://help.appveyor.com/discussions/questions/1621-permalinks-for-artifacts, which is a duplicate of http://help.appveyor.com/discussions/questions/516-url-for-latest-build-artifact that @frankmorgner mentioned.

**Comment by sschuberth** [comment] 2016-02-04 09:18
@FeodorFitsner Any update on the status of this?

**Comment by FeodorFitsner** [comment] 2016-02-04 20:06
Will deploy it this week.

**Comment by FeodorFitsner** [comment] 2016-02-04 20:06
URL for fetching "last successful" artifact:

    https://ci.appveyor.com/api/projects/<account>/<project>/artifacts/<artifact_file_path>

URL parameters:

* `branch` - if not specified the most recent successful build of *any branch* is fetched.
* `job` - the name of the job. If a build contains multiple jobs then this parameter is mandatory. Value must be URL-encoded, for example `Configuration%3DRelease`.

Examples:

Downloading latest successful artifact from all branches:

    https://ci.appveyor.com/api/projects/johnsmith/myproject/artifacts/bin/debug.zip

Downloading latest successful artifact for `master` branch:

    https://ci.appveyor.com/api/projects/johnsmith/myproject/artifacts/bin/debug.zip?branch=master

Downloading latest successful artifact from `master` branch and "Release" job:

    https://ci.appveyor.com/api/projects/johnsmith/myproject/artifacts/bin/debug.zip?branch=master&job=Configuration%3DRelease

**Comment by ulrichb** [comment] 2016-02-04 20:12
Great!

**Comment by nicowilliams** [comment] 2016-02-04 22:38
Excellent, thanks!

**Comment by sschuberth** [comment] 2016-02-06 08:38
I can confirm it to be working, thanks a lot!

**Comment by frankmorgner** [comment] 2016-02-07 18:32
My `job` parameter is a bit more complex, it is derived from "Environment: VSVER=12; Configuration: Release; Platform: x86". @FeodorFitsner, How would the `job` parameter look like in this case?

**Comment by FeodorFitsner** [comment] 2016-02-07 18:56
`Environment%3A%20VSVER%3D12%3B%20Configuration%3A%20Release%3B%20Platform%3A%20x86` - encoded with this tool: http://meyerweb.com/eric/tools/dencoder/

**Comment by frankmorgner** [comment] 2016-02-07 19:47
I tried https://ci.appveyor.com/api/projects/LudovicRousseau/opensc/artifacts/bin/debug.zip?branch=master&job=Environment%3A%20VSVER%3D12%3B%20Configuration%3A%20Release%3B%20Platform%3A%20x86 already, but this gives a `NoSuchKey` error... You can see all jobs here https://ci.appveyor.com/project/LudovicRousseau/OpenSC

**Comment by FeodorFitsner** [comment] 2016-02-07 19:52
There is no `bin/debug.zip` artifact under that job: https://ci.appveyor.com/project/LudovicRousseau/OpenSC/build/job/g5lvhjbidm2fx3r1/artifacts

**Comment by frankmorgner** [comment] 2016-02-07 20:22
From your explanation I assumed that `debug.zip` bundles all artifacts. Thanks for clarifying that I need to make my artifacts explicitly.

This leads me to a subsequent problem. Is it possible to use a static URL to map to the most recent build number? We are using `APPVEYOR_BUILD_VERSION`, which is defined as `0.15.0.{build}` in the artifact's name to distinguish the artifacts generated in each build.

**Comment by FeodorFitsner** [comment] 2016-02-07 20:24
Current implementation assumes file name is the same across all builds.

**Closed** 2016-02-08 02:49 UTC
Labels: in progress

**Comment by equalsraf** [comment] 2016-08-28 18:29
Is there a way to retrieve an artifact from a tag instead of a branch?

**Comment by FeodorFitsner** [comment] 2016-08-31 04:36
Currently not, but we've added a new issue to implement that: https://github.com/appveyor/ci/issues/1007

**Comment by majkinetor** [comment] 2016-09-16 19:09
Could you support an actuall list of artifacts via for example

        https://ci.appveyor.com/api/projects/majkinetor/au/artifacts 

I have few dynamically named artifacts would like to have it on a github release page as a link that would open the actuall artifact UI of latest succesifull build.

Alternativelly, glob that resolves to single file would be even better: 

        https://ci.appveyor.com/api/projects/majkinetor/au/artifacts/a*.zip

**Comment by vidstige** [comment] 2016-12-21 17:43
So what if I want to an image artifact? Right now I cannot as it tries to download the image or something. Github just says `Non-Image content-type returned`

**Comment by vidstige** [comment] 2016-12-21 17:43
@FeodorFitsner

**Comment by FeodorFitsner** [comment] 2016-12-21 17:47
@vidstige Can you please clarify the use case here?

**Comment by vidstige** [comment] 2016-12-21 19:43
As part of my build I'm generating sample output in form of images. I want to link these images from my github README.md.

**Comment by IlyaFinkelshteyn** [comment] 2016-12-22 01:41
@vidstige we would recommend to upload those images to some external storage as Azure or S3. AppVeyor artifacts infrastructure is designed mostly for people to be able to use it for deployment as part of build, but we don't feel comfortable if people rely on ApVeyor as hosting company to host images for public use.

**Comment by vidstige** [comment] 2016-12-22 09:20
@IlyaFinkelshteyn that makes lots of sense. Just wanted to make sure it wasn't some technical oversight. This is indeed how things work over at travis, etc. Thanks for an awesome service!

**Comment by HarpyWar** [comment] 2017-03-31 10:34
1) How to retrieve list of artifacts from last **successful** build via API?
2) How to get url with artifacts from last **successful** build?

I can't find this info on https://www.appveyor.com/docs/packaging-artifacts/

**Comment by IlyaFinkelshteyn** [comment] 2017-03-31 22:37
Please look at [this](https://www.appveyor.com/docs/api/samples/download-artifacts-ps/) sample. It is not exactly what you need but it gives an Idea how to get artifacts list too.
Note that  `$project` variable there is last, but not last successful build. To modify it to use last successful build you can use add code like this:
```
$history = Invoke-RestMethod -Uri "https://ci.appveyor.com/api/projects/$accountName/$projectSlug/history?recordsNumber=$recordsNumber" -Headers $headers -Method GET
$lgVersion = ($history.builds | Where-Object {$_.status -eq "success"})[0].version # last good version
$project = Invoke-RestMethod -Uri "https://ci.appveyor.com/api/projects/$accountName/$projectSlug/build/$lgVersion" -Headers $headers -Method GET
```
Also note that this sample assumes that you also introduce `$recordsNumber` variable to make request lighter.

Hope this helps.

**Comment by jasonkuhrt** [comment] 2018-09-17 20:06
How can I get an artifact permalink that does not require authorization or can have authorization passed inline (e.g. via query string). I know its possible using the notification template feature. Is it possible with the API?
