### ISSUE TITLE
Compiler internal error when compiling astropy

### ISSUE THREAD

**Issue by bsipocz** [appveyor/ci#890] opened 2016-06-29 17:05 UTC
It seems that one of the recent updates in appveyor triggered our builds to fail with compiler internal error.
I only see it with python3.5.

Examples: 
 - astropy PR: https://ci.appveyor.com/project/Astropy/astropy/build/1.0.4983/job/bymnrftgu8ldxl5u#L2341

 - ci-helpers build, that installs astropy dev: https://ci.appveyor.com/project/Astropy/ci-helpers/build/1.0.456/job/k8jqubgw94fyyr99#L2277

While the exact same build worked ~7 days ago: https://ci.appveyor.com/project/Astropy/ci-helpers/build/1.0.449/job/5ah9rwcy0dyo15ps

We are trying to reproduce the issue locally, but since no changes were made to the c code we suspect this is probably an issue with appveyor.

cc @mwcraig

**Comment by FeodorFitsner** [comment] 2016-06-29 17:26
Another project managed to fix python 3.5 issues: https://twitter.com/ionelmc/status/747851769468882944 - maybe that could be helpful.

All recent platform updates are here: http://www.appveyor.com/updates

Also, you can RDP into build worker for faster experimenting/troubleshooting: http://www.appveyor.com/docs/how-to/rdp-to-build-worker

**Comment by mwcraig** [comment] 2016-06-29 22:30
@FeodorFitsner -- I'm able to reproduce the problem locally now. 

The issue is with Visual Studio Update 3, not with appveyor per se; there are several reports on the [Microsoft Visual Studio Feedback site](https://connect.microsoft.com/VisualStudio/Feedback) of a similar error message (search for `C1001`).

I know we can use a previous build image with `os: Previous Visual Studio 2015`; will that take us back to before Update 3? If not, is there another way to get back there?

**Comment by FeodorFitsner** [comment] 2016-06-30 00:38
You wan't be able to sit on "previous" all the time as it's not like "previous version of VS 2015", but it's build worker image before the last update. Next time we do images update current image will become previous.

However, we can spawn a new image called "Visual Studio 2015 Update 2" and put it specifically under your account and [other accounts](http://help.appveyor.com/discussions/problems/4906-new-msbuild-in-vs2015-update-3-impacting-node-gyp-native-compilation) having issues with Update 3. This could be a temporary solution until things with Update 3 settle down.

I've created a new issue here collecting the cases: https://github.com/appveyor/ci/issues/891

Does it sound like a plan?

**Comment by mwcraig** [comment] 2016-06-30 01:26
That would be awesome, thanks! The `astropy` account is the one we need it for, I think.

**Comment by FeodorFitsner** [comment] 2016-07-12 00:36
A new image `Visual Studio 2015 Update 2` has been added to your account. It will be there until you have a fix for that issue with VS 2015 Update 3. No new software/updates will be installed to that image.

**Closed** 2016-07-12 00:38 UTC

**Comment by mwcraig** [comment] 2016-07-12 00:42
Thank you!

**Comment by bsipocz** [comment] 2016-07-12 10:40
Thanks @FeodorFitsner!
