### ISSUE TITLE
Android SDKs and Mobile development with C++ on Visual Studio 2019 image

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#3112] opened 2019-09-30 23:54 UTC

**Comment by VladislavAntonyuk** [comment] 2019-10-04 16:34
Android sdk platform 29

**Comment by VladislavAntonyuk** [comment] 2019-10-09 20:03
The issue is not fixed on Visual Studio 2019. I get this error: error XA5207: Could not find android.jar for API Level 29. This means the Android SDK platform for API Level 29 is not installed. Either install it in the Android SDK Manager (Tools > Open Android SDK Manager...), or change your Xamarin.Android project to target an API version that is installed.

**Comment by FeodorFitsner** [comment] 2019-10-09 20:50
Do you have a public repro project to test?

**Comment by FeodorFitsner** [comment] 2019-10-13 18:49
@VladislavAntonyuk we've just deployed an updated image with SDKs Level 19 through 29. Let me know how that worked for your project.

**Comment by VladislavAntonyuk** [comment] 2019-10-14 14:06
@FeodorFitsner the build succedeed. As a task imprivement if it is possible please switch to Google repository in SDK manager.

**Comment by FeodorFitsner** [comment] 2019-10-14 14:10
Thanks for the update. How would you switch repository (UI or command line)?

**Comment by VladislavAntonyuk** [comment] 2019-10-14 14:21
@FeodorFitsner I connected to the VM, and after starting the SDK manager, I saw the Microsoft repository, which bothers me a bit, because you use the Google repository. I would say it is a task improvement and is not required if you have higher priority tasks

**Closed** 2019-10-15 02:45 UTC
Labels: in progress
