### ISSUE TITLE
7z.exe process execution exception is not being written to log file

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1125] opened 2016-10-21 01:23 UTC
Details: http://help.appveyor.com/discussions/problems/5435-warnings-during-build-related-to-caching

**Comment by FeodorFitsner** [comment] 2016-12-20 21:02
Duplicate of https://github.com/appveyor/ci/issues/1199

**Closed by FeodorFitsner** 2016-12-20 21:02 UTC
