### ISSUE TITLE
Unable to move folder for android SDK installation

### ISSUE THREAD

**Issue by kpanwar** [appveyor/ci#1994] opened 2017-12-20 23:11 UTC
We are intermittently getting the following error in appveyor

SDK Manager: failed to install
-= Warning ! =-
A folder failed to be moved. On Windows this typically means that a program is using that folder (for example Windows Explorer or your anti-virus software.)
Please momentarily deactivate your anti-virus software or close any running programs that may be accessing the directory 'C:\Program Files (x86)\Android\android-sdk\platforms\android-26'.
When ready, press YES to try again.
Note: you  can use --force to override to yes.
[y/n] =>    Unexpected Error installing 'SDK Platform Android 8.0.0, API 26, revision 2': java.lang.StringIndexOutOfBoundsException: String index out of range: -1
android.bat : Error: Unexpected Error installing 'SDK Platform Android 8.0.0, API 26, revision 2': java.lang.StringIndexOutOfBoundsException: String index out of range: -1
At C:\AADDotNetLib\InstallAndroidSDK.ps1:24 char:16
  Echo 'y' | & $AndroidToolPath update sdk -u -a -t $sdkIndexArgument
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (Error: Unexpect...ut of range: -1:String) [], RemoteException
     FullyQualifiedErrorId : NativeCommandError
 
Error: String index out of range: -1
  Done. Nothing was installed.



This is generated from the script contributed by @IlyaFinkelshteyn from appveyor via https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/901/files. I don't see anything wrong with the script, but would like to know why this fails intermittently.

**Comment by IlyaFinkelshteyn** [comment] 2017-12-21 09:40
Could you please try the following brute-force workaround:

replace
```yaml
install:
 - ps: .\InstallAndroidSDK.ps1
```
with 
```yaml
install:
 - appveyor-retry powershell .\InstallAndroidSDK.ps1
```
Let us know if this helps.

**Comment by kpanwar** [comment] 2017-12-21 20:42
It still failed to install the SDK. :( @IlyaFinkelshteyn

**Comment by IlyaFinkelshteyn** [comment] 2017-12-21 21:12
Sorry for trail and error approach, but could you please try set `image` to `Previous Visual Studio 2017`, to understand if this is connected to the recent build worker image update?

**Comment by kpanwar** [comment] 2017-12-21 21:29
that worked, but build failed with strong naming issue which I can fix.

**Comment by IlyaFinkelshteyn** [comment] 2017-12-21 21:32
Lets keep this open. We need to root cause it before next build worker image update.

**Comment by IlyaFinkelshteyn** [comment] 2018-01-15 20:09
@kpanwar It seems that you can just remove my workaround and use current `Visual Studio 2017` image. In last image Android SDK is already installed (https://github.com/appveyor/ci/issues/1945). I should have noticed that earlier, sorry. Could you please check that it works today or tomorrow, because we are going to roll new image and current image will become "previous".  I [checked in my fork](https://ci.appveyor.com/project/IlyaFinkelshteyn/azure-activedirectory-library-for-dotnet/build/1.0.6). it works well.

**Comment by IlyaFinkelshteyn** [comment] 2018-01-24 07:56
No workaround needed anymore and `Previous Visual Studio 2017` replaced. after [today's update](https://www.appveyor.com/updates/2018/01/23/) 
PR: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/957

**Closed by IlyaFinkelshteyn** 2018-01-24 07:56 UTC
Labels: in progress
