### ISSUE TITLE
Webhooks failing to trigger builds

### ISSUE THREAD

**Issue by jakirkham** [appveyor/ci#1002] opened 2016-08-28 01:19 UTC
We starting to see webhooks trigger AppVeyor builds all pull requests are failing. Not sure if it is limited to pull requests or not. Retriggering the webhooks results in the exact same failure. More info below.

Header:

```
Cache-Control: no-cache
Content-Length: 23
Content-Type: application/json; charset=utf-8
Date: Sun, 28 Aug 2016 01:12:22 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
```

Body:

```
{"message":"Forbidden"}
```

**Comment by IlyaFinkelshteyn** [comment] 2016-08-29 17:33
Could you please go to to https://github.com/settings/applications, choose AppVeyor CI application and allow access to your organization. Please let us know if this helps.

Thank you,
Ilya.

**Comment by jakirkham** [comment] 2016-08-30 00:12
Sure. Though I'm not sure if this is still a problem or not. Seemed to be recovering later.

**Comment by jakirkham** [comment] 2016-08-30 00:13
I'll ask and see if we can do that. Though it seems we are recovering from this problem.

**Comment by jakirkham** [comment] 2016-08-30 02:42
Thoughts on this, @pelson?

**Comment by pelson** [comment] 2016-08-30 12:50
Both "AppVeyor" and "AppVeyor CI" are enabled.
![screenshot-2](https://cloud.githubusercontent.com/assets/810663/18089593/9a6a7788-6eb8-11e6-9ce4-813e5054bb5d.png).
Should we do something different?

**Comment by jakirkham** [comment] 2016-08-30 14:34
Note this appears to be a sporadic issue FWICT.

**Comment by IlyaFinkelshteyn** [comment] 2016-08-30 21:07
Can you please double check that you can start build manually, without any pull request, from Appveyor UI?

**Comment by jakirkham** [comment] 2016-08-30 21:44
We can restart existing jobs or PRs that have been built before pre-merge and sometimes we can redeliver the webhook to trigger a job to start. This isn't a consistent fail, but seems to be a sporadic issue.

FWIW I have tended to see a higher occurrence around 1a-3a UTC over the past couple days. Not sure why it tends to have a higher rate of occurrence then. Is it possible there is some maintenance task that occurs then that is causing us issues?

**Comment by IlyaFinkelshteyn** [comment] 2016-08-31 04:14
No maintenance task occurs on our side this time. Please provide few (2 is good enough) specific times (in UTC) when repro happened and respective and commit Ids.

Thank you,
Ilya.

**Comment by IlyaFinkelshteyn** [comment] 2016-09-02 01:03
By the way we added additional tracing which will be in production next week, so we will be able to give better answer what happened to that webhooks. We will still be needed specific time or at least time range when this happens (assuming it will be still the case next week).

--ilya.

From: Ilya Finkelshteyn
Sent: Tuesday, August 30, 2016 9:14 PM
To: appveyor/ci <reply@reply.github.com>; appveyor/ci <ci@noreply.github.com>
Cc: Comment <comment@noreply.github.com>; AppVeyor Team <team@appveyor.com>
Subject: RE: [appveyor/ci] Webhooks failing to trigger builds (#1002)

No maintenance task occurs on our side this time. Please provide few (2 is good enough) specific times (in UTC) when repro happened and respective and commit Ids.

Thank you,
Ilya.

**Comment by jakirkham** [comment] 2016-09-02 15:32
Yep, sorry. Here are two cases I have seen it with. PR ( https://github.com/conda-forge/staged-recipes/pull/1407 ) and PR ( https://github.com/conda-forge/nsis-feedstock/pull/3 ) are two cases where we have seen this issue. In both cases, resending the webhook repeatedly eventually worked, but we ended up having to wait awhile too. IIRC we saw a few other ones, but I don't think I kept as good of records on them.

**Comment by IlyaFinkelshteyn** [comment] 2016-09-08 05:44
Do you have any failures info from any day starting 9/6? I am asking because 9/5 we updated our tracing and can see more webhook-related error details.

**Comment by jakirkham** [comment] 2016-09-08 23:24
So I don't have any way ATM of monitoring this globally. It sort of depends on whether I or others see them and report them.

Given we didn't see lots of reports for this issue and certainly none recently, it seems reasonable that this is fixed. Will let you know if we have any recurrences. Thanks for your help.

**Comment by FeodorFitsner** [comment] 2016-09-09 03:03
Sure!

**Comment by jakirkham** [comment] 2016-09-21 06:02
Seeing this issue again.

**Comment by FeodorFitsner** [comment] 2016-09-21 06:49
What status/error/body did you get? What was webhook request URL?

**Comment by jakirkham** [comment] 2016-09-21 07:27
Same as before. Realized I didn't mention the error though, which was a 403 error. The body and message are the same, but here is a recent one. Saw this for 3 repos that I know of. They are as follows.

* https://github.com/conda-forge/pandas-profiling-feedstock
* https://github.com/conda-forge/slugify-feedstock
* https://github.com/conda-forge/uncommitted-feedstock

At the time, redelivering the webhook just resulted in a failure no matter how many retries. Now I have redelivered all of them successfully.

Here is the info from the last failure with `slugify-feedstock` before redelivery succeeded.

Headers:
```
Cache-Control: no-cache
Content-Length: 23
Content-Type: application/json; charset=utf-8
Date: Wed, 21 Sep 2016 06:00:21 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
```

Body:
```
{"message":"Forbidden"}
```

**Comment by jakirkham** [comment] 2016-09-21 18:06
Should add all of these repos have been around awhile (10+ days) and have had successful runs on AppVeyor previously.

**Comment by IlyaFinkelshteyn** [comment] 2016-09-22 05:00
I see that we are getting Forbidden from GitHub when we are trying to call this https://developer.github.com/v3/pulls/#get-a-single-pull-request API. We call this API after receiving webhook in order to ensure that commit is  merge-able, not closed, etc.

Will look deeper and eventually ping GitHub support.

**Comment by jakirkham** [comment] 2016-10-10 23:15
Encountering this with PR ( https://github.com/conda-forge/yapf-feedstock/pull/7 ) currently.

**Comment by FeodorFitsner** [comment] 2016-10-10 23:45
What do you see in response from AppVeyor? And what was `X-Github-Event` of the request?

**Comment by jakirkham** [comment] 2016-10-10 23:56
The response was the same as in the OP. The event was `pull_request`. This was for a brand new pull request. Tried a couple of times to redeliver the webhook earlier and it was not working. Have just now retried and it worked.

**Comment by FeodorFitsner** [comment] 2016-10-11 00:02
OK, and what was the value of `X-GitHub-Delivery` header?

**Comment by jakirkham** [comment] 2016-10-11 00:15
So would that have changed after redelivery or not? If not, it is `09b5cd80-8f3f-11e6-9646-39d32ad1e06c`. If so, I have no clue.

**Comment by IlyaFinkelshteyn** [comment] 2016-10-11 20:07
Here are errors from our traces (simplified) for that period. As you see GItHub returned 403 in various of calls. I think we need to involve them to understand what happens.

```
10/10/2016 11:05:15 PM +00:00   "HTTP POST to https://api.github.com/repos/conda-forge/staged-recipes/statuses/3225f372a00a819832421e28fb0e2e24a707e821 returned 403: Forbidden"
10/10/2016 11:13:34 PM +00:00   "HTTP GET to https://api.github.com/repos/conda-forge/yapf-feedstock/pulls/7 returned 403: Forbidden"
10/10/2016 11:15:12 PM +00:00   "HTTP GET to https://api.github.com/repos/conda-forge/yapf-feedstock/pulls/7 returned 403: Forbidden"
10/10/2016 11:14:48 PM +00:00   "HTTP GET to https://api.github.com/repos/conda-forge/yapf-feedstock/pulls/7 returned 403: Forbidden"
10/10/2016 11:14:34 PM +00:00   "HTTP GET to https://api.github.com/repos/conda-forge/genpy-feedstock returned 403: Forbidden"
10/10/2016 11:16:15 PM +00:00   "HTTP POST to https://api.github.com/repos/conda-forge/staged-recipes/statuses/3056a216737a7799a30573ba3f755ec051350459 returned 403: Forbidden"
10/10/2016 11:21:12 PM +00:00   "HTTP GET to https://api.github.com/repos/conda-forge/genpy-feedstock returned 403: Forbidden"
10/10/2016 11:26:28 PM +00:00   "HTTP POST to https://api.github.com/repos/conda-forge/tk-feedstock/statuses/0b16070fd9c8e66e5e27d1c53c95639e4ea20bb6 returned 403: Forbidden"
10/10/2016 11:34:23 PM +00:00   "HTTP POST to https://api.github.com/repos/conda-forge/python-utils-feedstock/statuses/c86c616c94539c6609adc78f07ce4fef5ff9dc97 returned 403: Forbidden"
10/10/2016 11:36:58 PM +00:00   "HTTP GET to https://api.github.com/repos/conda-forge/genpy-feedstock returned 403: Forbidden"
10/10/2016 11:36:32 PM +00:00   "HTTP POST to https://api.github.com/repos/conda-forge/vs2008_express_vc_python_patch-feedstock/statuses/bfaa3ca0b8fd921842a7b4dc3b1ba443f00d6dc1 returned 403: Forbidden"
10/10/2016 11:47:32 PM +00:00   "HTTP POST to https://api.github.com/repos/conda-forge/nbexamples-feedstock/statuses/0d594f93e5bfa697bacb3be5a76138de9aa6d66f returned 403: Forbidden"
10/10/2016 11:49:52 PM +00:00   "HTTP GET to https://api.github.com/repos/conda-forge/staged-recipes/pulls/1732 returned 403: Forbidden"
```

**Comment by FeodorFitsner** [comment] 2016-10-12 01:34
@jakirkham Can you please check that GitHub is currently authorized in AppVeyor, i.e. you can see a list of GitHub repositories on [New project](https://ci.appveyor.com/projects/new) page and correct GitHub username on [Account](https://ci.appveyor.com/account) page?

**Comment by jakirkham** [comment] 2016-10-12 02:32
Yep, I can see a list of GitHub repositories in the new project page and the org is listed on the account page.

**Comment by IlyaFinkelshteyn** [comment] 2016-10-13 19:40
GitHub support people helped us to find the root cause. Our API calls (impersonated as user conda-forge-admin used in this case) are hitting owner [rate limit] (https://developer.github.com/v3/#rate-limiting) for this user. From our side we are making the change to expose body of GitHub API response in our API errors, thus making it easier to diagnose issues like this right away. From your side you have to look at your automation and see what code (directly or indirectly) could send too much API calls to the  GitHub API.

--ilya.

**Comment by jakirkham** [comment] 2016-10-13 20:59
That is very helpful information. Thank you for tracking that down. Also thanks for exposing the GitHub API response. I expect this will be very helpful in understanding further what is going on. Will look into this more.

**Comment by jakirkham** [comment] 2016-10-16 17:52
Though I have to say it is a bit odd that the rate limit is counting against `conda-forge-admin` instead of the user that opened PR ( https://github.com/conda-forge/yapf-feedstock/pull/7 ), namely myself. Do you know why that is?

**Comment by FeodorFitsner** [comment] 2016-10-16 20:56
`conda-forge-admin` is an authorized user in AppVeyor and it uses that token when calling GitHub APIs. AppVeyor cannot authenticate as someone doing PR.

**Comment by jakirkham** [comment] 2016-12-16 14:48
Why not? I'm guessing other CIs are able to get around this rate limit somehow and would suspect that they use the PR author's token. Though I must admit the details are a bit fuzzy to me too. Do you have a contact at GitHub that we could talk to about this?

**Comment by FeodorFitsner** [comment] 2016-12-16 20:19
We don't have a dedicated contact there, but drop a message via https://github.com/contact - people at GitHub are usually very responsive

**Comment by jakirkham** [comment] 2017-01-21 21:37
Would it be possible to include the rate limit info in the webhook response too? That would really help with checking when it will be reset or if we are getting close to running out.

**Comment by FeodorFitsner** [comment] 2017-01-22 20:37
You mean rate limit from GitHub API call fetching PR details?

**Comment by jakirkham** [comment] 2017-02-07 14:41
Exactly.

**Comment by jakirkham** [comment] 2017-02-27 00:55
Maybe this [guide]( https://developer.github.com/guides/basics-of-authentication/ ) is helpful.

**Comment by jakirkham** [comment] 2017-04-11 14:43
> > Would it be possible to include the rate limit info in the webhook response too? That would really help with checking when it will be reset or if we are getting close to running out.
>
> You mean rate limit from GitHub API call fetching PR details?

Should I put this in a new issue?

**Comment by IlyaFinkelshteyn** [comment] 2017-04-12 02:15
I created https://github.com/appveyor/ci/issues/1491, please feel free to add details into that issue.

**Comment by isuruf** [comment] 2017-05-02 13:45
> Though I must admit the details are a bit fuzzy to me too.

I couldn't find out what travis does when checking for merge status, but I found out how they post build status to a PR [here](https://github.com/travis-ci/travis-core/blob/fd905d451087627e1d7320585b10c5bf75d6ad40/lib/travis/addons/github_status/event_handler.rb#L44-L46). Since posting a build requires push access, it'll be slightly different.

First it checks from the github event, whether the PR author is a travis-ci user. If so use his/her token.
If the PR author is not a travis-ci user, use the token of the admin.

Appveyor can do the same too. Most of the `conda-forge` users are appveyor users too, so this can help `conda-forge` a lot.

**Closed** 2019-10-21 19:42 UTC
