### ISSUE TITLE
Build stop without reason

### ISSUE THREAD

**Issue by Liryna** [appveyor/ci#1141] opened 2016-10-30 18:11 UTC
Hello,

I noticed that the some of our build sometimes hangs at the start of the job or after repository checkout. We also had one situation where it was hanging in the middle of the build.

Examples:
1. https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.1-826/job/x7f57qbif5xk7kda
2. https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.1-831/job/4ai7fn022112ru3t
3. https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.1-840/job/6cf06sh16pcpqqc8  <= This is one where it does not hang

We have no idea if this is on our side or on appveyor but the checkout should at least work no 😢 ?

Thanks in advance !

**Comment by IlyaFinkelshteyn** [comment] 2016-10-31 18:08
Hello,

This might happen if some process consumes close to 100% of CPU or memory and there are no resources on build VM for Appveyor agent to send messages. Could you please add traces more often, between all important steps, therefore we could see what step can lead to this situation?

Thank you,
Ilya.

**Comment by Liryna** [comment] 2016-10-31 19:15
Thanks for your answer @IlyaFinkelshteyn 

Currently we "only" see that happening during `git checkout -qf ....` that is handled by appveyor. Next steps should be `Restoring build cache` from appveyor but it does not shows up.

As far as I know, there is no event called between these two commands ? If there is, where can I add logs ?

**Comment by IlyaFinkelshteyn** [comment] 2016-10-31 20:05
Yes, you are right. Don't you mind to try [new build cache](https://www.appveyor.com/blog/2016/09/28/the-new-build-cache/)?

**Comment by Rondom** [comment] 2016-10-31 20:16
One should add that this configuration does not use the build cache at all, i.e. the directory does not even exist. The build cache is only used in the "All" configuration.
So there is something happening after the during or after the checkout that hangs.

This should be the first line that gets executed. We can add a print there:
https://github.com/dokan-dev/dokany/blob/8eb11718ad28bdde6a453184c2a3f62a23a6d4d0/appveyor.yml#L81

I think it would be nice to see whether the new build cache fixes our problem. (Also I would be even more curious to see in how far it improves the performance. :-D)
What do you think @Lyrina?

**Comment by Liryna** [comment] 2016-10-31 20:24
👍 for the new build cache !

Also totally forgot to specify that the build configuration that fail is the only one who request to reboot with `Restart-Computer -Force;`
https://github.com/dokan-dev/dokany/blob/master/appveyor.yml#L81-L87

Is it not simply that the VM never comes back ?

**Comment by Rondom** [comment] 2016-10-31 20:52
Hm, that could be it as well.
I see that we already have a printout of "Before reboot" and I think that the other commands (bcdedit and verifier) also produce some output.
If I look at the third log which shows a working build, I cannot find this output. So there's a separate issue: we are losing some lines before the reboot.

@IlyaFinkelshteyn I think it would be nice to enable it not only for maxhy/dokany, but also for Lyrina/dokany and Rondom/dokany, so that we have the same setup for testing.

**Comment by Liryna** [comment] 2016-10-31 21:08
Reboot seems to erase past commands so we will not see bcdedit and verifier print if reboot has started 😢

**Comment by FeodorFitsner** [comment] 2016-10-31 21:09
Try adding delay *before* `Restart-Computer` command.

**Comment by IlyaFinkelshteyn** [comment] 2016-10-31 21:19
New build cache enabled for all 3 accounts. Note that it is per account, not project. 

Also I think that if you enable (**non-blocking!**) [RDP ](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/) at some step before reboot, you hopefully may be able to connect to the build worker if it stuck and see if some messages raised.

Note that per my recent experiences `-force` option sometimes does not really forces the reboot, and using just `restart-computer` might be something worth trying. Or use old good `shutdown` command.

--ilya.

**Comment by Rondom** [comment] 2016-10-31 21:51
Updating the build cache is down from 48 to 18 seconds and restoring the build cache is down from  41 to 19 seconds in my first tests 👍 I only randomly picked a build as a sample, but I guess it is safe to say that it is faster and that you did a very good job. Thank you!

@Liryna I will probably have time for this on Wednesday or Thursday.

**Comment by Rondom** [comment] 2016-10-31 22:57
@FeodorFitsner  Adding a sleep *before* the reboot made the output appear (or it was adding the RDP output, but I guess that's unlikely)

I also notice that the build time gets reset to 0:00:00 after the reboot. Should I file a separate issue for this?
https://ci.appveyor.com/project/Rondom/dokany/build/1.0.1-172/job/ubuf4fe6qjvlt7yg#L122

@Liryna Code is at https://github.com/Rondom/dokany/tree/appveyor-fstest-hang

**Comment by FeodorFitsner** [comment] 2016-11-01 00:22
Yes, please add the issue.

**Comment by Liryna** [comment] 2016-11-01 13:09
I don't know if this is related to this issue changes made but: Appveyor stop now during the build, reboot without reason and restart all the script without cleanup O_O

We can see the `before_build` https://github.com/Liryna/dokany/blob/master/appveyor.yml#L89
here: https://ci.appveyor.com/project/Liryna/dokany/build/1.0.1-3#L98
and here: https://ci.appveyor.com/project/Liryna/dokany/build/1.0.1-3#L802

It really stop without waiting to finish the current VS build 😮

**Comment by Liryna** [comment] 2016-11-02 21:43
Ok my last message was a bsod on our side 👍 

When a BSOD happen, appveyor rerun the full build.

**Comment by Rondom** [comment] 2016-11-03 00:38
Let's summarize:
* Initial issue (hang right after checkout)
  - Probably cache-related
  - So far we have not been able to reproduce it with the new cache (with the old cache it happened every few builds). I tried running a commit that had failed before multiple times and could not reproduce it
 - I suggest leaving this issue open for a few days and if the problem does not appear again, we can close it.
* Output before reboot not appearing
 - @Liryna fixed this by adding a sleep *before* the reboot
 - It would be nice to document a "best-practice" for rebooting (and also document where the build agent proceeds after a planned reboot). I made some [assumptions in this commit here](https://github.com/Rondom/dokany/commit/4a68bb8c87233595ad899d7fcad566783e8d350b), but I am not sure, if I am right. @FeodorFitsner, can you confirm my understanding:
     + 1. If the build agent senses a planned reboot, it will abort the current build step
     + 2. Exit to let the OS reboot
     + 3. After the reboot proceed with the build-step *after* the one that was interrupted by the planned reboot
* The issue that @Lyrina described above (VM was seemingly restarting while MSVC was building)
 - totally unrelated to our issue here
 - turned out that the reboot was caused by a BSOD caused by a recent change in our code 😊 and the build agent could of course not capture all the output before the BSOD, which confused us a bit
 - The behaviour of the build agent after the unplanned reboot caused by the BSOD seems to be indeterministic. I can detect the BSOD after reboot, but which build step gets executed next seems to be random, so the detection code is not always executed.
    
    [1st build](https://ci.appveyor.com/project/Rondom/dokany/build/1.0.1-220/job/kp8a61n6rmlp22sj#L825): Build is proceeding with the next build step
    
    [2nd build of the same commit](https://ci.appveyor.com/project/Rondom/dokany/build/1.0.1-221/job/2buo9r9apllckx28#L857): build starts at `before_build` (or maybe `init` if it exists, but we do not have `init`). Thus my code for detecting that a BSOD happened gets executed.
 - Ideally I would like this to be deterministic. @FeodorFitsner Should I open another issue for that? Or should I open a topic on the forum? What do you prefer? Or do you think what we are doing is hopeless and what we are currently doing is the best we can do? I find it pretty cool that I can [detect that the BSOD happened and upload the zipped MEMORY.DMP as an artifact](https://github.com/Rondom/dokany/commit/be13468ca48b2eae22557c6e85fecdeec1c917d2).

**Comment by Rondom** [comment] 2016-11-08 02:08
I think we can close this. I rebuilt old commits multiple times and could not reproduce the hangs anymore with the new build cache.

I filed two issues as a follow-up:
* #1145 (timestamps are 0:00:00 after reboot)
* #1158 (handle BSODs and reboots cleanly)

**Comment by FeodorFitsner** [comment] 2016-11-08 02:11
Sure, thanks

**Closed by FeodorFitsner** 2016-11-08 02:11 UTC
