### ISSUE TITLE
Please, Install Qt 5.8

### ISSUE THREAD

**Issue by Wohlstand** [appveyor/ci#1336] opened 2017-02-21 10:26 UTC
Qt 5.8 has been released in January 28 and has added into list of Online Installer as release. It has better stability and I want to use it in my project (which tries to always use latest version on all platforms).

http://blog.qt.io/blog/2017/01/23/qt-5-8-released/

**Comment by FeodorFitsner** [comment] 2017-02-21 17:50
Closing as duplicate of https://github.com/appveyor/ci/issues/1279

**Closed by FeodorFitsner** 2017-02-21 17:50 UTC

**Comment by Wohlstand** [comment] 2017-02-21 18:01
Okay, sorry wasn't found that in search...
Thanks for noticing that already exists!

**Comment by FeodorFitsner** [comment] 2017-02-21 18:09
In fact, Qt 5.8 has been just deployed to all images. We are publishing update post shortly.

**Comment by Wohlstand** [comment] 2017-02-21 22:28
In the [documentation](https://www.appveyor.com/docs/installed-software/#qt) is was be shown latest Qt 5.7 (at morning). However, now I see it, so thanks a lot!

**Comment by Wohlstand** [comment] 2017-02-23 11:45
Anyway, just now I got a fail to build on Qt 5.8:
https://ci.appveyor.com/project/Wohlstand/pge-project/build/0.4.0.3.754
Seems, it's a legacy image, and why it still be on the server?

However, first time I set Qt 5.8, worked fine. The build itself wasn't broken (because files I modified at me are platform-independent source code files and build files for Linux and OS X which are no way to break Windows build)

**Comment by FeodorFitsner** [comment] 2017-02-23 19:00
The image with Qt 5.8 is back as default one. Let us know how it worked.

**Comment by Wohlstand** [comment] 2017-02-23 19:07
Okay, works!
[Since this build](https://ci.appveyor.com/project/Wohlstand/pge-project/build/0.4.0.3.760) it seems works! (Anyway, the reason of failed build because I accidentally copied wrong string and now Linux fails too, therefore going to fix that)
Thanks for fixing image!
