### ISSUE TITLE
Failed on nodejs fs.stat dev

### ISSUE THREAD

**Issue by NoahDragon** [appveyor/ci#1560] opened 2017-05-17 20:25 UTC
Our program failed on the fs.stat testing case:
![image](https://cloud.githubusercontent.com/assets/5704064/26174191/96f995ee-3b1c-11e7-960f-750e8d0ad00d.png)

It worked in 2 month ago:  https://ci.appveyor.com/project/tommy351/hexo/build/469

But since the time of this submission (https://ci.appveyor.com/project/tommy351/hexo/build/470), this issue persists. 

We checked our code, where we did have any change related to this issue. Moreover, the dev field in file status is `ID of device containing file` ([ref](http://stackoverflow.com/questions/11787016/nodejs-file-statistics)), and our program won't modify this field.

Any help would appreciate.

**Comment by IlyaFinkelshteyn** [comment] 2017-05-18 12:28
Did you try to rebuild that last successful commit? This can happen that it fail too now, and most probably this is because of some external dependencies. If you compare build logs (for the same job in matrix -- `nodejs_version=7`) from builds 469 and 470, you can notice that a lot of npm dependencies (and even npm itself) are different.

**Comment by NoahDragon** [comment] 2017-05-18 13:29
@IlyaFinkelshteyn Thanks, I will take a look at them.

**Comment by NoahDragon** [comment] 2017-05-19 14:20
@IlyaFinkelshteyn I have compared those two logs.
![image](https://cloud.githubusercontent.com/assets/5704064/26251640/f53949d2-3c7b-11e7-87d6-e302910dd564.png)
Only these three packages are changed, and I don't think these could affect the `fs.stat()` returns. 

Based on my understanding, the device ID should only change when the devices are different. The test case we run is to compare the file status between threads. I think the device ID should be still same. Please correct me if I'm wrong.

**Comment by NoahDragon** [comment] 2017-05-24 17:55
The same test case has passed on Travis-CI, but failed on Appveyor. My assumption is some changes on Appveyor cause this issue, maybe multiple threading or container management.

**Comment by JLHwung** [comment] 2017-08-25 15:30
This issue can be reproduced in a very simple setup, a living case can be found at https://ci.appveyor.com/project/JLHwung/appveyor-fs-statsync-issue/build/5/job/hgk1peebu3lj6u3f.

The testing code is simple and convenient for narrowing down: https://github.com/JLHwung/appveyor-fs-statSync-issue/blob/2854b90c8dcfc56918ffd6f7ed93d166f2f0f551/index.js

**Comment by JLHwung** [comment] 2017-10-27 15:10
This issue might not be related to appveyor, see https://github.com/nodejs/node/issues/16496. Suggest closing it.

**Comment by FeodorFitsner** [comment] 2017-10-27 15:33
Thanks for the update!

**Closed by FeodorFitsner** 2017-10-27 15:33 UTC
