### ISSUE TITLE
'New build' button rebuilds master instead of displayed branch

### ISSUE THREAD

**Issue by vszakats** [appveyor/ci#644] opened 2016-02-13 23:51 UTC
The button's description says it would start a new build using the latest revision of the branch used in current session (which would also be the expected and useful behavior), the button appears to consistently trigger a new build using master HEAD instead.

Tested with a GitHub repo, managed via an `appveyor.yml`.

**Comment by FeodorFitsner** [comment] 2016-02-14 21:09
"New build" button starts a new build of "Default branch" that is specified on "General" tab of project settings. This is by design.

**Comment by vszakats** [comment] 2016-02-14 21:28
Thanks for clarifying. I'd argue it'd be more intuitive if it would work on the "current branch", like the button popup description says:
![screen shot 2016-02-14 at 22 25 16](https://cloud.githubusercontent.com/assets/1446897/13036530/f4eccffc-d369-11e5-88f7-77d35b8bf32f.png)

If this is not indented, probably above text should be synced with real behaviour.

**Comment by FeodorFitsner** [comment] 2016-02-14 21:29
Good catch, I see now. Will fix a hint.

**Comment by 304NotModified** [comment] 2016-02-19 23:52
I think it would be nice to rename the button also.

I have pressed multiple times the wrong button because I needed a new build (but on the current branch) - with a good text, the tooltip should not be needed.

**Comment by FeodorFitsner** [comment] 2016-02-19 23:53
For example? ;)

**Comment by vszakats** [comment] 2016-02-19 23:55
Perhaps not to display the button at all when current branch != default branch?

**Comment by vszakats** [comment] 2016-02-19 23:56
...or replace it with a `go back` (or the like) button that takes user back to the default branch.

**Comment by vszakats** [comment] 2016-02-19 23:58
My issue is that I fail to see the use-case to rebuild _another_ branch by a prominently placed button displayed on the _current_ branch. Knowing the idea behind it, might help finding the best solution.

**Comment by 304NotModified** [comment] 2016-02-20 00:02
"Rebuild master" ?

Removing is also fine by me.

**Comment by FeodorFitsner** [comment] 2016-02-20 00:13
OK, thanks for your thoughts.

**Comment by m4tt1mus** [comment] 2016-02-23 20:08
I agree with vszakats and 304NotMofied. 

I run into the problem where I commit, CI builds, I change an environment variable, and try to kick off a new build. This works fine unless someone committed after me then it has a problem with the build number being a duplicate. Ex: "Build version 1.0.992.0 already exists. Update next build number or change version format." So if you're trying to debug appveyor settings on a branch this is nightmare.

**Comment by vszakats** [comment] 2016-07-14 11:45
Any objection to close this Issue? It does seem to have stalled and/or caught very minor interest. (even though the issue is still present)

**Comment by 304NotModified** [comment] 2016-07-14 14:47
No fix = no close IMO

**Comment by FeodorFitsner** [comment] 2016-07-14 14:48
Nope.

**Closed by FeodorFitsner** 2016-07-14 14:48 UTC
Labels: bug

**Comment by FeodorFitsner** [comment] 2016-07-14 14:50
That button was designed to build default branch. It should be a separate issue to allow rebuilding of current (last?) branch.

**Comment by vszakats** [comment] 2016-07-14 16:07
I understand. If so, the tooltip text needs to be fixed to reflect this behaviour, as you also confirmed [earlier](https://github.com/appveyor/ci/issues/644#issuecomment-183980636).

[ Indeed the expect behaviour would be to rebuild the _tip_ (meaning the latest commit) of the branch at hand. ]
