### ISSUE TITLE
Pushed sequence of commits fails to trigger build if last one is marked "[ci skip]"

### ISSUE THREAD

**Issue by c-lipka** [appveyor/ci#740] opened 2016-04-11 15:58 UTC
Suppose I have made a series of changes to my local repo, with the following descriptions, and am now pushing them in a single go:
1. "Fixed something. Needs testing."
2. "Modified something else. Needs testing as well."
3. "[ci skip] Updated docs. Can't possibly break the build."

Obviously I would want AppVeyor to run, because the first two commits shouldn't skip continuous integration. Ideally AppVeyor would run on 2., but personally I'd also be ok with it running on 3.

However, what currently happens is that AppVeyor doesn't trigger at all, so my changes 1. and 2. are never tested as they should be.

**Comment by FeodorFitsner** [comment] 2016-04-11 16:16
This is how it currently works - it runs the build for the most recent commit in a push. If you need to test every commit do a push every time you commit. Push often to get sooner feedback if some commit breaks the build.

**Comment by c-lipka** [comment] 2016-04-11 17:23
If the current behaviour is intentional, then please consider this a change request.

**Comment by FeodorFitsner** [comment] 2018-06-12 22:03
I'm closing this as this is by design. We are not going to change that behavior right now as lot of customers are already used to it.

**Closed by FeodorFitsner** 2018-06-12 22:03 UTC
