### ISSUE TITLE
.NET 3.0 Preview (3.0.100-preview-009812) on Visual Studio 2019 Preview image

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2762] opened 2018-12-10 19:59 UTC
https://dotnet.microsoft.com/download/dotnet-core/3.0

**Comment by AraHaan** [comment] 2018-12-14 02:13
This commit will fail for me, is this only for the vspreview image or also for the stable ones as an opt-in as well? I would like to be able to use it on stable if my global.json asks for it on the build. 
https://github.com/Elskom/ReleasePackaging/commit/3086340492bea5e1f383a16880c19e0ba01e9277

the failing build: https://ci.appveyor.com/project/Elskom/releasepackaging/builds/21002033

**Comment by FeodorFitsner** [comment] 2018-12-14 02:19
No, .NET 3.0 Preview is installed on `Visual Studio 2019 Preview` image.

**Comment by VladislavAntonyuk** [comment] 2018-12-14 06:38
@FeodorFitsner , I have just tried to build the project with 2019Preview image, but msbuild was 15.9 and sdk was 2.2.100.
When it will be fixed?

**Comment by FeodorFitsner** [comment] 2018-12-14 17:41
Well, this is the test: https://ci.appveyor.com/project/appveyor-tests/net-core-3
and corresponding appveyor.yml: https://github.com/appveyor-tests/net-core-3/blob/master/appveyor.yml

**Comment by VladislavAntonyuk** [comment] 2018-12-14 18:47
https://ci.appveyor.com/project/VladislavAntonyuk/circlepacking/builds/21009402/job/7147lxg54s45cgr7

**Comment by FeodorFitsner** [comment] 2018-12-14 18:52
Use `global.json` to pin the version of SDK as suggested.

**Comment by AraHaan** [comment] 2018-12-14 19:48
https://ci.appveyor.com/api/buildjobs/26sewik7k6monkwn/log
nice, I would like to avoid the global.json though.

**Comment by FeodorFitsner** [comment] 2018-12-14 19:56
If you work through `dotnet` CLI instead of `msbuild` then the latest .NET Core will be used.

**Comment by FeodorFitsner** [comment] 2018-12-14 20:30
That's true. MSBuild path wasn't changed on VS 2019 image. What's its location btw?

**Comment by AraHaan** [comment] 2018-12-14 20:31
@FeodorFitsner but the problem is that your build system defaults to msbuild instead of telling it to instead do "dotnet build" when it detects a dotnet sdk style project.

**Comment by VladislavAntonyuk** [comment] 2018-12-14 20:41
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\15.0\Bin 
Or
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\

**Comment by IlyaFinkelshteyn** [comment] 2018-12-17 22:06
Path to msbuild issue is tracked at https://github.com/appveyor/ci/issues/2776.

**Closed by IlyaFinkelshteyn** 2018-12-17 22:06 UTC
Labels: GCE, VS 2017 Preview

**Comment by VahidN** [comment] 2019-07-30 15:10
Please install .NET Core SDK version 3.0.100-**preview7**-012821
