### ISSUE TITLE
for-matrix-only: environment breaks when I add a global variable

### ISSUE THREAD

**Issue by SergeGautherie** [appveyor/ci#2361] opened 2018-05-22 22:55 UTC
Possibly related/duplicate of issues 2351 and/or 2359.

--

[Build 456](https://ci.appveyor.com/project/SergeGautherie/reactos/build/CI-I2361-good.reactos.appveyor.456) works as expected.
[Build 457](https://ci.appveyor.com/project/SergeGautherie/reactos/build/CI-I2361-broken.reactos.appveyor.457) is obviously broken.
The only difference is that I added
```yaml
  APPVEYOR_RDP_PASSWORD:
    secure: amQ18PhcGpzi95VrjdE94A==
```

--

```yaml
environment:
  matrix:
    - BuildType: "vssolution"
  APPVEYOR_RDP_PASSWORD:
    secure: amQ18PhcGpzi95VrjdE94A==

version: CI-I2361-broken.reactos.appveyor.{build}
skip_branch_with_pr: true
clone_depth: 1
clone_folder: C:\reactos-cov

init:
  - echo I__BT="%BuildType%"
  - ps: >-
      If ($env:BuildType -eq "clang-cl") {
        $env:clang_configure_option="clang"
      } Elseif ($env:BuildType -eq "vssolution") {
        $env:clang_configure_option="VSSolution"
      } Else {
        $env:clang_configure_option=""
      }
  - echo I__CCO="%clang_configure_option%"

build_script:
  - echo BS__BT="%BuildType%"
  - echo BS__CCO="%clang_configure_option%"

test: off
deploy: off

for:
-
  matrix:
    only:
      - BuildType: "vssolution"

  build_script:
    - echo FOR__BS__BT="%BuildType%"
    - echo FOR__BS__CCO="%clang_configure_option%"
```

**Comment by SergeGautherie** [comment] 2018-05-22 23:00
Cc @IlyaFinkelshteyn

**Comment by SergeGautherie** [comment] 2018-05-23 08:36
> create a simpler repro

Done.

> for some reason msbuild REACTOS.sln fails.

`msbuild` fails, because `configure.cmd` "fails", ..., because `environment` is broken.

**Comment by IlyaFinkelshteyn** [comment] 2018-05-24 02:16
Thank you for detailed description and extracting the real root cause. Luckily it is another manifestation of https://github.com/appveyor/ci/issues/2351, for which fix is already checked in and is going to be deployed soon. I am closing this in favor of https://github.com/appveyor/ci/issues/2351.

**Closed by IlyaFinkelshteyn** 2018-05-24 02:16 UTC

**Comment by IlyaFinkelshteyn** [comment] 2018-05-24 04:51
@SergeGautherie try now, should be OK

**Comment by SergeGautherie** [comment] 2018-05-24 11:57
Verified fixed.
